apiVersion: v1
kind: Service
metadata:
  name: pac-service
  labels:
    app: pac
spec:
  selector:
    app: pac
  type: NodePort
  ports:
  - protocol: TCP
    port: 9090
    nodePort: 30090
    targetPort: 9090
